# Generated by Django 6.0.6 on 2026-06-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instagram_user_id", models.CharField(max_length=255, unique=True)),
                ("access_token", models.CharField(max_length=500)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("profile_picture_url", models.URLField(blank=True, null=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
