# Generated by Django 6.0.5 on 2026-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuser',
            name='is_user_follow_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
