# Generated by Django 6.0.5 on 2026-09-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instagramuser_is_user_follow_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='main.instagrammessage')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'updated_at'], name='main_messag_status_7f782a_idx')],
            },
        ),
    ]
